const ALLOWED_LANGS = ["en", "fr"]
const MINIMUM_DAILY_TIMESTAMP = 1683756000000
const MAXIMUM_WORD_LENGTH = 11
const MINIMUM_WORD_LENGTH = 4

module.exports = { ALLOWED_LANGS, MAXIMUM_WORD_LENGTH, MINIMUM_DAILY_TIMESTAMP, MINIMUM_WORD_LENGTH }
