const ALLOWED_LANGS = ["en", "fr"]
const MAXIMUM_WORD_LENGTH = 11
const MINIMUM_WORD_LENGTH = 4
const NB_BEST_SCORES = 10
const SENDGRID_EMAIL = "noreply.findyourword@gmail.com"

module.exports = { ALLOWED_LANGS, MAXIMUM_WORD_LENGTH, MINIMUM_WORD_LENGTH, NB_BEST_SCORES, SENDGRID_EMAIL }
